from pages.sign_in_page import SignInPage
from pages.base_page import BasePage
from pages.ai_platform_home_page import AiPlatformHomePage
from pages.pendo_tour_page import PendoTourPage
from pages.new_page import NewPage
from pages.ai_profile_page import AiProfilePage
from pages.data_page import DataPage
from pages.top_menu_page import TopMenuPage
from pages.models_page import ModelsPage
from pages.deployments_page import DeploymentsPage
from pages.apps_page import AppsPage
from pages.what_if_app_page import WhatIfAppPage
from pages.credits_packs_page import CreditsPacksPage
from pages.invoice_card_page import InvoiceCardPage
from pages.drap_usage_page import DrapUsagePage
from pages.drap_top_menu_page import DrapTopMenuPage
from pages.tours_guide_component import ToursGuideComponent
from pages.modeling_right_sidebar import ModelingRightSidebar
from pages.contact_sales_dialog import ContactSalesDialog
from pages.docs_file_types_page import DocsFileTypesPage
from pages.paxata_login_page import PaxataLoginPage
